Add theme query param to customise survey rendering
DavinciSalute/formbricks pull request #19
Opened 2024-11-15 14:31 UTC by brunodavinci

Add new `theme` parameter to iframe's url.
When it is set to `welbee` it permits to customise the UI for welbee.

2024-11-15 16:45 UTC, PaoloLeggio requested changes
Ho notato che il codice include modifiche che hardcodano valori specifici legati a un prodotto (es. `theme === "welbee"` per la customizzazione dello stile). Questo contravviene all'obiettivo principale del microservizio di rimanere generico e riutilizzabile.

Un microservizio dovrebbe essere progettato per essere agnostico rispetto ai dettagli di implementazione di un prodotto specifico. Hardcodare valori specifici introduce un forte accoppiamento, limitando la flessibilità e la riusabilità del codice.

Esempio problematico:

```
<div
  className={cn(
    theme === "welbee" ? "items-start" : "items-end md:items-center",
    "flex max-h-dvh min-h-dvh justify-center overflow-clip"
  )}
>
```

Se ritieni che passare le props necessarie per customizzare l'iframe possa rendere il codice troppo prolisso, considera la possibilità di salvare le configurazioni a livello di database. Ad esempio, la tabella product già esistente, che contiene informazioni di customizzazione dello stile, potrebbe essere estesa per includere ulteriori configurazioni.

D'altra parte, se ritieni che queste modifiche possano essere accettabili e utili per tutti gli attuali prodotti (come ad esempio, modificare il comportamento della validazione del FileUploadQuestion da un alert a un messaggio inline), valutiamo insieme agli altri team la possibilità di renderlo il comportamento di default.

2024-11-15 17:17 UTC, brunodavinci commented
> Ho notato che il codice include modifiche che hardcodano valori specifici legati a un prodotto (es. `theme === "welbee"` per la customizzazione dello stile). Questo contravviene all'obiettivo principale del microservizio di rimanere generico e riutilizzabile.
> 
> Un microservizio dovrebbe essere progettato per essere agnostico rispetto ai dettagli di implementazione di un prodotto specifico. Hardcodare valori specifici introduce un forte accoppiamento, limitando la flessibilità e la riusabilità del codice.
> 
> Esempio problematico:
> 
> ```
> <div
>   className={cn(
>     theme === "welbee" ? "items-start" : "items-end md:items-center",
>     "flex max-h-dvh min-h-dvh justify-center overflow-clip"
>   )}
> >
> ```
> 
> Se ritieni che passare le props necessarie per customizzare l'iframe possa rendere il codice troppo prolisso, considera la possibilità di salvare le configurazioni a livello di database. Ad esempio, la tabella product già esistente, che contiene informazioni di customizzazione dello stile, potrebbe essere estesa per includere ulteriori configurazioni.
> 
> D'altra parte, se ritieni che queste modifiche possano essere accettabili e utili per tutti gli attuali prodotti (come ad esempio, modificare il comportamento della validazione del FileUploadQuestion da un alert a un messaggio inline), valutiamo insieme agli altri team la possibilità di renderlo il comportamento di default.

Ciao @PaoloLeggio ,

se ho capito bene, tu suggerisci che anzichè passare un'unica prop theme=welbee, io passi più props generiche, del tipo: align=top, shadow=false (per non avere l'ombreggiatura), etc.
corretto?
se mi confermi che questo è accettabile procedo a modificare l'implementazione in questa direzione

2024-11-18 08:59 UTC, PaoloLeggio approved these changes

2024-11-18 08:59 UTC, PaoloLeggio commented on apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
> +  alignForm: string | undefined;
```suggestion
  alignForm?: 'top';
```

2024-11-18 08:59 UTC, PaoloLeggio commented on apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
> +  alignForm: string | undefined;
magari domani metterai anche `center` e `bottom`. ad ogni modo meglio evitare una stringa generica seil valore accettato attualmente é solo `top`

2024-11-18 08:59 UTC, PaoloLeggio commented on apps/web/app/s/[surveyId]/page.tsx
> +    alignForm?: string;
```suggestion
    alignForm?: 'top' ;
```

2024-11-18 08:59 UTC, PaoloLeggio commented on apps/web/app/s/[surveyId]/components/LinkSurveyWrapper.tsx
> +  alignForm: string | undefined;
```suggestion
  alignForm?: 'top' ;
```

2024-11-18 10:23 UTC, merged